[package]
name = "midirouter"
version = "0.1.0"
authors = ["Deuce314 <>"]

[dependencies]
rimd = { path = "./rimd/" }
midir = "0.5"
[dependencies.cursive]
version = "0.9"
default-features = false
features = ["blt-backend"]
