[package]
name = "midirouter"
version = "0.1.0"
authors = ["Deuce314 <>"]

[dependencies]
rimd = { git = "https://github.com/RustAudio/rimd" }
midir = "0.5"
[dependencies.cursive]
version = "0.9"
default-features = false
features = ["termion-backend"]
